/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/AppProvider/index.vue')['default']
    BasicButton: typeof import('./../components/BasicButton/index.vue')['default']
    BasicInput: typeof import('./../components/BasicInput/index.vue')['default']
    Iconify: typeof import('./../components/Iconify/index.vue')['default']
  }
}
